[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = [
    "corepack enable",
    "corepack prepare pnpm@10.15.0 --activate",
    "pnpm install --frozen-lockfile"
]

[phases.build]
cmds = ["pnpm run docs:build"]

[processes]
web = "pnpm dlx http-server docs/.vuepress/dist -p ${PORT:-8080}"
